package com.finalyear.hikemanagementapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Data class representing a Hike entity in the database.
 * Contains all information about a hiking trip including required fields
 * like name, location, date, and optional fields like description, weather,
 * photo path, and GPS coordinates.
 *
 * @property id Unique identifier for the hike, auto-generated by Room.
 * @property name Name of the hike (required).
 * @property location Location or address of the hike (required).
 * @property date Date of the hike stored as timestamp in milliseconds (required).
 * @property parkingAvailable Whether parking is available at the hike location (required).
 * @property length Length of the hike in kilometers (required).
 * @property difficulty Difficulty level of the hike: Easy, Moderate, or Hard (required).
 * @property description Optional description or notes about the hike.
 * @property weather Optional weather conditions during the hike.
 * @property groupSize Optional number of people in the hiking group.
 * @property photoPath Optional file path to a photo of the hike.
 * @property latitude Optional GPS latitude coordinate of the hike location.
 * @property longitude Optional GPS longitude coordinate of the hike location.
 */
@Entity(tableName = "hikes")
data class Hike(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,                    // Required
    val location: String,                // Required
    val date: Long,                      // Required (stored as timestamp)
    val parkingAvailable: Boolean,       // Required (Yes/No)
    val length: Double,                  // Required (in km)
    val difficulty: String,              // Required
    val description: String? = null,     // Optional
    val weather: String? = null,         // Optional - custom field 1
    val groupSize: Int? = null,          // Optional - custom field 2
    val photoPath: String? = null,       // For storing photo path
    val latitude: Double? = null,        // For location coordinates
    val longitude: Double? = null        // For location coordinates
)

