package com.finalyear.hikemanagementapp.data

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Data class representing an Observation entity in the database.
 * Observations are notes or sightings recorded during a hike, such as
 * wildlife, plants, landmarks, or other points of interest.
 * Each observation is linked to a specific hike via foreign key.
 *
 * @property id Unique identifier for the observation, auto-generated by Room.
 * @property hikeId Foreign key reference to the parent Hike entity (required).
 * @property observation Description of what was observed (required).
 * @property observedAt Timestamp when the observation was made in milliseconds (required).
 * @property comments Optional additional comments about the observation.
 */
@Entity(
    tableName = "observations",
    foreignKeys = [
        ForeignKey(
            entity = Hike::class,
            parentColumns = ["id"],
            childColumns = ["hikeId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class Observation(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val hikeId: Long,                    // Required - reference to hike
    val observation: String,             // Required
    val observedAt: Long,                // Required (stored as timestamp)
    val comments: String? = null         // Optional
)

